In [9]:
b=np.zeros([3,4])
print("\n Array initialized with all zeroes.\n",b)



 Array initialized with all zeroes.
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
import numpy as np
a=np.array([[1,2,4],[5,8,7]])
print("Array created using passed list:\n",a)


Array created using passed list:
 [[1 2 4]
 [5 8 7]]


In [33]:
d=np.random.random((2,2))
print("n A random array.\n",d)

n A random array.
 [[0.75837141 0.48843278]
 [0.88333829 0.13942491]]


In [34]:
e=np.arange(0,30,5)
print(" n A sequential array width step of 5.\n",e)

 n A sequential array width step of 5.
 [ 0  5 10 15 20 25]


In [37]:
c=np.full((3,3),6)
print("\nArray initialised with all 6\n",c)


Array initialised with all 6
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [ ]:
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1